"""业务枚举取值（字符串存库，与设计文档一致）。"""

# 配件状态（demo 用到的子集；七态枚举值仍保留可读性）
STATUS_IN_STOCK = "在库"
STATUS_IN_USE = "在用"
STATUS_LOANED = "借出"
STATUS_DAMAGED = "损坏"
STATUS_IN_TRANSIT = "在途"
STATUS_TRANSFERRED = "已调拨"
STATUS_SCRAPPED = "报废"

# 事件类型（本主线）
EVENT_INBOUND = "入库"
EVENT_INSTALL = "装机"
EVENT_UNINSTALL = "拆下"
EVENT_LOAN = "借出"
EVENT_RETURN = "归还"
EVENT_TRANSFER = "调拨"
EVENT_SCRAP = "报废"
# 第 8 种原子事件：盘点错位后的说明性校正履历（状态不变，仅位置修正）
EVENT_CORRECT = "校正"

# 位置种类
LOC_STORAGE = "库位"
LOC_SERVER = "服务器"
LOC_EXTERNAL = "外单位"
LOC_NONE = "无"

# 服务器运行状态（三值留全；退役无 API）
RUN_NOT_LIVE = "未投运"
RUN_LIVE = "投运"
RUN_RETIRED = "退役"

# 审批
ACTION_LOAN = "借出"
ACTION_TRANSFER = "调拨"
ACTION_SCRAP = "报废"
ACTION_TYPES = (ACTION_LOAN, ACTION_TRANSFER, ACTION_SCRAP)
APPROVAL_PENDING = "审批中"
APPROVAL_APPROVED = "通过"
APPROVAL_REJECTED = "驳回"
APPROVAL_WITHDRAWN = "撤回"

# 报废/调拨缘由
REASON_SCRAP_DESTROY = "本单位销毁"
REASON_SCRAP_FACTORY = "返厂换新"
REASON_CODES_SCRAP = (REASON_SCRAP_DESTROY, REASON_SCRAP_FACTORY)

STEP_PENDING = "待审"
STEP_APPROVED = "通过"
STEP_REJECTED = "驳回"

# 来源 / 责任组（responsible_group = 运维部门，列名保持不动）
SOURCE_ORIGINAL = "服务器原装"
SOURCE_CONTRACT = "独立合同采购"
SOURCE_FRAMEWORK = "框招正偏移"
SOURCE_TYPES = (SOURCE_ORIGINAL, SOURCE_CONTRACT, SOURCE_FRAMEWORK)
RESPONSIBLE_GROUPS = ("基础组", "运营组", "网络组", "平台组")

# 报废影像证据强制：按配件类型判断（算力卡类高值件）
SCRAP_ATTACHMENT_CATEGORIES = ("算力卡",)

# 可调配标记（实物公共字段）
ALLOC_GENERAL = "通用可调"
ALLOC_RESERVED = "保留"
ALLOCATABLE_FLAGS = (ALLOC_GENERAL, ALLOC_RESERVED)

# demo：本单位产权标识（与 part.owner_unit 比对）
HOME_OWNER_UNIT = "本单位信息中心"

# 内存代际
DDR_GENS = ("DDR4", "DDR5")

# 四类业务角色（矩阵落地）
# - 领导：全部权限（含审批与基础数据）
# - 主业运维 / 外委运维：权限对等（流转/盘点/装机等），不可审批
# - 设备供应商：仅入库相关，不可看配件列表与可调余量
ROLE_SUPPLIER = "设备供应商"
ROLE_MAINTENANCE = "外委运维"
ROLE_OPERATIONS = "主业运维"
ROLE_LEADER = "领导"
ROLES = (ROLE_SUPPLIER, ROLE_MAINTENANCE, ROLE_OPERATIONS, ROLE_LEADER)

# 业务运维（外委 = 主业；领导具备同等业务权限）
OPS_ROLES = (ROLE_MAINTENANCE, ROLE_OPERATIONS, ROLE_LEADER)
# 仅领导可审批
APPROVER_ROLES = (ROLE_LEADER,)
# 配件列表 / 可调余量 / 导出（供应商不可）
VIEW_PARTS_ROLES = OPS_ROLES
INVENTORY_ROLES = OPS_ROLES
# 盘点发起/结案（与审批分离）
STOCKTAKE_ROLES = OPS_ROLES
# 入库：供应商 + 业务运维
INBOUND_ROLES = (ROLE_SUPPLIER, ROLE_MAINTENANCE, ROLE_OPERATIONS, ROLE_LEADER)
INSTALL_UNINSTALL_ROLES = OPS_ROLES
LOAN_RETURN_ROLES = OPS_ROLES

# 盘点
SCOPE_FULL = "全盘"
SCOPE_KINDS = ("全盘", "按机房", "按责任组", "按配件类型", "指定清单")

STOCKTAKE_IN_PROGRESS = "进行中"
STOCKTAKE_COMPLETED = "已完成"
STOCKTAKE_ARCHIVED = "已归档"

RESULT_PENDING = "待复核"
RESULT_MATCH = "相符"
RESULT_SHORTAGE = "盘亏"
RESULT_SURPLUS = "盘盈"
RESULT_MISPLACE = "错位"

DISC_SHORTAGE = "盘亏"
DISC_SURPLUS = "盘盈"
DISC_MISPLACE = "错位"

DISC_STATUS_HOLD = "挂起追查"
DISC_STATUS_REVIEW = "待复核"
DISC_STATUS_RESOLVED = "已处置"

# ---- 账号状态与自助注册 ----
USER_STATUS_ACTIVE = "正常"
USER_STATUS_PENDING = "待审核"
USER_STATUS_REJECTED = "驳回"
USER_STATUS_DISABLED = "停用"
# 自助注册可申请的角色（领导只能由现有领导授权，不开放自助申请）
SELF_REGISTER_ROLES = (ROLE_SUPPLIER, ROLE_MAINTENANCE, ROLE_OPERATIONS)
